name: Build All
on:
  schedule:
    - cron: 15 6 * * *
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: false
        default: 'develop'
      label:
        type: string
        required: false
        default: 'VS Code Extensions'
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
      label:
        type: string
        required: false
        default: 'VS Code Extensions'
      runId:
        type: string
        required: false

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch || 'develop' }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      - run: npm --version
      - run: node --version
      - run: npm run compile
      - run: npm run vscode:package
      - name: Stage Artifacts
        run: |
          mkdir extensions
          find packages -name "*.vsix" -type f -exec cp {} ./extensions \;
      - name: Upload Extensions
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.label || 'nightly' }}
          path: ./extensions/

  e2e-tests:
    needs: build-all
    uses: ./.github/workflows/e2e.yml
    with:
      runId: ${{ github.run_id || inputs.runId }}